FROM ubuntu:26.04

# avoid interactive prompts during package install
ENV DEBIAN_FRONTEND=noninteractive

# HINT: NO POWERSHELL SUPPORT!

WORKDIR /app
COPY . /app

RUN chmod +x /app/install.sh && \
  chmod +x /app/install.ps1

CMD [ "bash" ]
